# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Projeto Taroni Muay Thai Para Todos
email: chacal.bl@hotmail.com
endereco: Av. Santa Cruz (Taroni), 7190 - Senador Camará / Rio de Janeiro/RJ
description: > # this means to ignore newlines until "baseurl:"
  O projeto Taroni Muay Thai Para Todos surgiu com o intuito de incentivar a prática
  esportiva por crianças, jovens e adultos. Conheça mais sobre o projeto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.projetotaroni.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-angular
